### ISSUE TITLE
Galaxy 4 watch setup issue

### ISSUE THREAD

**Issue by oguh43** [adil192/SamsungAppsPatcher#11]
Hi, when pairing gavaxy 4 watch, everything goes fine until the app goes to configure the watch. then another dialog to pick a device to pair appears, ruining the setup.

**Comment by adil192** [comment]
Yes this is a known issue, since the Watch4 uses a completely different operating system. You can try another project like this: https://forum.xda-developers.com/t/restrictions-removed-samsung-health-monitor-wearos-1-1-1-191-root-age-country-device-restriction-removed-23rd-march-2022.4322527/ but I haven't tested it personally.

**Comment by oguh43** [comment]
Umfortunatelly the linked xda post only focuses on syncing samsung health data, not connecting the watch.

**Comment by adil192** [comment]
Look for the sections "Pairing issues with Watch4 on Galaxy Wearables" and "Now here is an update of mine if the above does not work and Galaxy Wearables keeps disconnecting from the watch4". Beyond that I can't help you as I don't have any Samsung devices including the Watch4

**Comment by oguh43** [comment]
Ill flash stock, thank you for your time :)
